### ISSUE TITLE
only crce.identity capabilities are displayed

### ISSUE THREAD

**Issue by pbrada** [ReliSA/CRCE#14]
For any given resource, only the "crce.identity" capabilities are displayed in the Web UI of "store".  Similarly for properties and requirements. In "buffer", other caps/reqts are shown as well.

What all should be displayed can be checked via the webservice URL (http://localhost:8080/rest/v2/metadata/).

**Comment by romanpesek** [comment]
Fixed - in the crce-repository-impl module in the FilebasedStoreImpl class of the package cz.kiv.crce.crce.repository.filebased.internal, the function is modified:

  @Override
     public synchronized <Resource> getResources () {
         try {
             // Edit rpesek - For webui-v2 retrieval of resources including details (capabilities, requirements)
             // return metadataDao.loadResources (repository, false);
         return metadataDao.loadResources (repository, true);
         } catch (IOException e) {
             logger.error ("Could not load resources of repository {}.", baseDir.toURI (), e);
         }
         return Collections.emptyList ();
     }
