### ISSUE TITLE
resources cannot be removed from buffer

### ISSUE THREAD

**Issue by pbrada** [ReliSA/CRCE#15]
Irrespective of how the resource had been uploaded to Buffer, confirming "Remove" results in error message "Could not remove artifact from buffer".

**Comment by romanpesek** [comment]
Fixed - in the crce-repository-impl module in the BufferImpl class of the package cz.kiv.crce.crce.repository.filebased.internal, the function is modified:

  private boolean isInBuffer (Resource resource) {
         URIs = metadataService.getUri (resource) .normalize ();
         if (! "file" .equals (uri.getScheme ())) {
             return false;
         }
         return true; // rpesek edit: return new File (s) .getPath () startsWith (baseDir.getAbsolutePath ());
     }
