### ISSUE TITLE
build issues: dependency versions, repositories

### ISSUE THREAD

**Issue by pbrada** [ReliSA/CRCE#7]
When trying to build:

1. maven complains about missing "version" for hibernate-jpa-2.1-api.jar 
2. missing repository for jna-osgi.jar
3. artefact jna-platform not available at appropriate time/step
4. similarly lpsolve artefact

(As of 10/2017, when I first encountered these.)

**Comment by danekja** [comment]
JNA and lpsolve have to be built from third-party folder. Those are not part of the main build process. Might be a good idea to create a super pom which would build everything, including the third-party dir.

The third-party dir contains OSGi wrappers around libraries which don´t (didnt have at time of creation) OSGi manifests included in their artifacts.

**Comment by pbrada** [comment]
Clean checkout of the "dev" branch, perfoming a clean full build (initially empty maven local cache): many issues in dependencies in POMs.

**Comment by pbrada** [comment]
Build now clean and self-contained after many updates, clean-ups and changes (commit c640bb4ddfce321dd68f535ae160b18e60483595).
